### PR TITLE
Fix Desync Error, Fixes #1

### LINKED ISSUE #1: Mod will cause desyncs in MP
Need to use the global.table to save the state, (preferably indexed by user)

### PR DESCRIPTION
**Pull request by Nexela**
Set up global table for per user usage
Fix logic when un-slowing in case something else changed player modifier
Add text overlay when slowed
Add remote interfaces for setting/reading the modifier value
Increment version

### CODE REVIEW

**Comment by lf-** [comment]
Needs some comment spelling+grammar fixes.

File: control.lua [hunk 1]
```diff
@@ -1,21 +1,102 @@
...
+  if player.gui.center["slow-key"] then player.gui.center["slow-key"].destroy() end
+  if slowed then
+    local gui = player.gui.center.add{type="label", name="slow-key", caption=" (SLOW) ", direction = "vertical"}
+    gui.style.minimal_width=32
+  end
+end
+
+--create the global if not exists, Doing this here will have no noticeable impact on performance.
+local function get_or_create_global(player_index)
+  if not global.player_data then global.player_data = {} end
```
Comment (lf-) [inline control.lua]: global.player_data = global.player_data or {}

File: control.lua [hunk 2]
```diff
@@ -1,21 +1,102 @@
...
-    slowed = not slowed
-end)
+  end
+end
+--Read the current modifier
+interface.read_slow_key_modifier = function(player)
+  player = get_valid_player(player)
+  if player then
+    local pdata = get_or_create_global(player.index)
+    player.print("slow-key: Current modifier is "..pdata.modifier)
```
Comment (lf-) [inline control.lua]: Spacing around operators: `..`

File: control.lua [hunk 3]
```diff
@@ -1,21 +1,102 @@
...
+        debug("changing speed modifier to "..cur_modifier + change.. " cur="..cur_modifier.." old="..pdata.last_modifier.." dif="..pdata.difference)
+        player.character.character_running_speed_modifier = cur_modifier + change
+        info_gui(player, false)
+        pdata.slowed=false
+        --free up uneeded variables
+        pdata.difference, pdata.saved_modifier, pdata.last_modifier = nil, nil, nil
+      else -- We are at normal speed, lets slow down
+        pdata.last_modifier = cur_modifier -- Save a copy of the players current modifier in case it gets changed.
+        pdata.saved_modifier = pdata.modifier -- Save a copy of the slow modifier in case we change it.
+        pdata.difference = cur_modifier - pdata.modifier -- get the difference in case players modifier changes some other way.
```
Comment (lf-) [inline control.lua]: Inconsistent spacing around comment start character & first character in comment capitalization

File: control.lua [hunk 4]
```diff
@@ -1,21 +1,102 @@
 -- Bounds for expected behaviour: 0.0 > x > -1.0
--- Above 0: becomes FastKey
+-- Above 0: becomes FastKey (0 is default modifier when creating player unless changed by mods)
```
Comment (lf-) [inline control.lua]: Addition should be on a separate line? Is this even true? `MODIFIER = -0.5` further down in the file

File: control.lua (hunk 3 above)
Comment (lf-) [inline control.lua]: Why is it necessary to store difference? It's 100% unused as far as actual functionality, the variable should probably be removed.

**Review by lf- — CHANGES_REQUESTED** [review]
Pretty good, just needs a couple code style/nitpick changes

File: control.lua (hunk 4 above)
Comment (Nexela) [reply control.lua]: Moved, and clarified

File: control.lua (hunk 1 above)
Comment (Nexela) [reply control.lua]: Redone, however either one should work with the same efficiency

File: control.lua (hunk 3 above)
Comment (Nexela) [reply control.lua]: Thinking some more on this is it might not be easy to reset

Example 1
Toggle slow-key on
MobB does modifier=modifier+arbitrary number

Example 2
Toggle slow-key on
ModC be does modifier = number

No matter which way we go with it, After toggling off we could have incorrect values.

I am going to account for example 2 and just disable slow-key without changing if the modifier is not the same as the saved one. Let me know if you have any better ideas.

File: control.lua (hunk 2 above)
Comment (Nexela) [reply control.lua]: Made all spacing consistent.

File: control.lua (hunk 3 above)
Comment (Nexela) [reply control.lua]: I blame it on split personalities :)

**Review by Nexela — COMMENTED** [review]
All changes made, played with it in game for a couple of days with no issues.

**Review by lf- — APPROVED** [review]

**Comment by lf-** [comment]
Awesome, merging
